### ISSUE TITLE
Consolidating CPU/GPU builds

### ISSUE THREAD

**Issue by jakirkham** [rapidsai/xgboost-feedstock#8]
After discussion offline with @hcho3 & @trivialfis , it sounds like we can consolidate the CPU & GPU packages into a single build that is GPU-enabled, but can be used without issues on CPU

To do this will involve some changes to the package here. This is an attempt at documenting them. Though it is always possible something may be missing from this list

<hr>

First step would be to add an additional skip here (like [this one from UCX]( https://github.com/conda-forge/ucx-split-feedstock/blob/78e8d08b1391a6a29d05eb22bf8a30d1878954f2/recipe/meta.yaml#L12-L13 )):

```yaml
  skip: true  # [not linux or cuda_compiler_version == "None"]
```

This would be added here:

https://github.com/rapidsai/xgboost-feedstock/blob/64fc15a4b38c58f74dd4f50fa34d8bc796105fcf/recipe/meta.yaml#L20-L22

As a side note, these `skip`s are unneeded and can be dropped:

https://github.com/rapidsai/xgboost-feedstock/blob/64fc15a4b38c58f74dd4f50fa34d8bc796105fcf/recipe/meta.yaml#L23-L25

<hr>

Any `build/string`s like these

https://github.com/rapidsai/xgboost-feedstock/blob/64fc15a4b38c58f74dd4f50fa34d8bc796105fcf/recipe/meta.yaml#L81-L83

Can be consolidated to a single `string` like so. There is no need to distinguish CPU & CUDA builds when they are all CUDA builds

```yaml
      string: rapidsai_py{{ CONDA_PY }}h{{ PKG_HASH }}_{{ PKG_BUILDNUM }}
```

<hr>

Would delete all the mutex packages. Anything with `cpu` or `gpu` in its name. For example:

https://github.com/rapidsai/xgboost-feedstock/blob/64fc15a4b38c58f74dd4f50fa34d8bc796105fcf/recipe/meta.yaml#L106-L115

Similarly anything with `mutex` in its name. For example:

https://github.com/rapidsai/xgboost-feedstock/blob/64fc15a4b38c58f74dd4f50fa34d8bc796105fcf/recipe/meta.yaml#L72-L76

Also any lines that reference them can be deleted. Like these

https://github.com/rapidsai/xgboost-feedstock/blob/64fc15a4b38c58f74dd4f50fa34d8bc796105fcf/recipe/meta.yaml#L95

<hr>

Next would be to replace any of these selectors with `# [linux]` (as we would also build with CUDA on Linux):

https://github.com/rapidsai/xgboost-feedstock/blob/64fc15a4b38c58f74dd4f50fa34d8bc796105fcf/recipe/meta.yaml#L31

<hr>

Afterwards any lines referencing `__cuda` like this

https://github.com/rapidsai/xgboost-feedstock/blob/64fc15a4b38c58f74dd4f50fa34d8bc796105fcf/recipe/meta.yaml#L70

Would be dropped

<hr>

Lastly for any package using ``, would update their `build` section. Like this one

https://github.com/rapidsai/xgboost-feedstock/blob/64fc15a4b38c58f74dd4f50fa34d8bc796105fcf/recipe/meta.yaml#L48-L51

To include the following (so we are not downloading `cudatoolkit` unnecessarily)

```yaml
      ignore_run_exports_from:
        - {{ compiler('cuda') }}  # [(cuda_compiler_version or "").startswith("11")]
```

**Comment by jakirkham** [comment]
May also need to [use `conda-smithy` to re-render]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) to apply these changes to CI configuration files, README, etc.

**Comment by trivialfis** [comment]
Not sure if it's important, but Windows is also supported for CUDA (but not nccl, no distributed training on Windows).
